name: Docker CI
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASS: ${{secrets.DOCKER_PASS}}
      GITHUB_SHA: ${{github.sha}}

    steps:
      - uses: actions/checkout@v3

      - name: Docker sign-in
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - name: Build docker image
        run: docker build -t $DOCKER_USER/test .

      - name: Push to dockerhub
        run: docker push $DOCKER_USER/test
