name: Go

on:
  workflow_dispatch:
    inputs:
      go-version:
        description: "go version"
        required: true
        type: choice
        default: "1.18"
        options:
          - "1.18"
          - "1.19"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
          
      - name: Build
        run: go build

      - name: Test
        run: go test

      - name: Run
        run: go run main.go
