name: Go Matrix Build

on: push

jobs:
  matrix-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16, 1.17, 1.18]
        ubuntu-version: [20.04, 22.04]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Set up Ubuntu
      with:
        distro: ubuntu-${{ matrix.ubuntu-version }}
    - name: Build
      run: go build -v .
