name: Go Matrix Build

on: push

jobs:
  matrix-build:
    strategy:
      matrix:
        go-version: [1.16, 1.17, 1.18]
        ubuntu-version: [20.04, 22.04]
    runs-on: ${{ matrix.ubuntu-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Build
      run: go build -v .
